### ISSUE TITLE
ImGui config file missing.

### ISSUE THREAD

**Issue by 1099255210** [Mauler125/r5sdk#65]
Open launcher.exe and after choosing launching mode, i got an error:

Native(M):ImGui config file 'D:\Apex\R5pc_r5launch_N1094_CL456479_2019_10_30_05_20_PM\platform\imgui.json' not found. Changing the settings in the console or server browser options re-create's it. Exception: '[json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal'

**Comment by Mauler125** [comment]
Fixed in '6f268c09784f30364aa84720a70756f9b7264ce6'.
