### ISSUE TITLE
net_setkey as ConVar instead of ConCommand

### ISSUE THREAD

**Issue by IcePixelx** [Mauler125/r5sdk#73]
https://github.com/Mauler125/r5sdk/blob/master/r5dev/vstdlib/callback.cpp#L713

Make it a ConVar with a callback instead.

**Comment by Mauler125** [comment]
Addressed and fixed as of commit e98a6c31e917cf7bd326a368838196b8f640b410. All extraneous copies of the encoded netkey have been removed. The logic behind the callback remains unchanged.
