### ISSUE TITLE
No HD textures on shipped build

### ISSUE THREAD

**Issue by r3muxd** [Mauler125/r5sdk#97]
I'll make a PR for this after finals, but essentially you can get the game down to <10GB by throwing out the starpaks (which aren't necessary) and forcing the game to return true in CHLClient::HasPartialInstall (index 2, +16 from interface start). Then you need to make some UI script edits to get rid of the "HD TEXTURES DOWNLOADING" shit. You should probably toss out Origin when you do this too (which isn't too hard), because Origin integration serves no purpose (persistence from retail servers isn't used, the game is free so there's no ownership to verify, and everyone just makes new accounts for r5 anyway). You can make the HD textures an optional download I guess if people want that, and then it wouldn't be too hard to check for their presence in the haspartialinstall hook.

**Comment by r3muxd** [comment]
Namely, for removing origin you'll want to check out S3 base+0x2D3B00, which contains a nasty cvar interface call that resets the name convar to blank on every connection if Origin isn't present.

**Comment by r3muxd** [comment]
Also, for bansystem I cannot endorse the Firehol IP blocklist enough. Maybe add a ConVar to check if the IP is on it or something, because it is such a pain in the ass to get around.

**Comment by hax4dazy** [comment]
> the game is free so there's no ownership to verify
The origin integration is used for things other then verifying that the user has the game

**Comment by Mauler125** [comment]
Thanks for the suggestion. The HD textures are no longer shipped by default with the game's install as of the last update in November 2023.

Also, as of commit c9a9b01bf211db7bd8eaa9ab3ec2f6b53d328660, optional streaming texture paks (opt.starpak) are no longer considered mandatory, a dedicated chech has been added [here](https://github.com/Mauler125/r5sdk/commit/c9a9b01bf211db7bd8eaa9ab3ec2f6b53d328660#diff-ad34989274436b3a5189386b6b03ef8a02d0b887602959278e0a542103d5a65fR75).
